name: X-Prison
version: 1.17.0
main: dev.passarelli.xprison.XPrison
authors: [ WildInterloper, Drawethree, Ale1x, tomwmth ]
api-version: 1.18
load: POSTWORLD
website: passarelli.dev

depend:
  - Vault
  - WorldGuard
  - WorldEdit
  - helper
softdepend:
  - PlaceholderAPI
  - Multiverse-Core
  - UltraBackpacks
